// Engineer data uses real geographic coordinates (lat/lng decimal degrees)
// lat: latitude (positive = north, negative = south)
// lng: longitude (positive = east, negative = west)
// When you have real backend data, replace these with: { lat: user.location.lat, lng: user.location.lng }

export const DEMO_ENGINEERS = [
  {
    id: "eng_001",
    name: "Egronomic Engineers",
    specialty: "Electrical & Solar",
    rating: 4.9,
    reviews: 134,
    available: true,
    avatar: "EE",
    avatarColor: "#0080ff",
    lat: 6.5244,
    lng: 3.3792,
    distance: "1.2 km",
    responseTime: "~5 min",
    skills: ["Solar Installation", "Wiring", "Generator Repair"],
  },
  {
    id: "eng_002",
    name: "TechFix Pro",
    specialty: "HVAC & Plumbing",
    rating: 4.7,
    reviews: 89,
    available: true,
    avatar: "TP",
    avatarColor: "#00c48c",
    lat: 6.5355,
    lng: 3.3087,
    distance: "3.1 km",
    responseTime: "~12 min",
    skills: ["Air Conditioning", "Pipes", "Water Heaters"],
  },
  {
    id: "eng_003",
    name: "Swift Repairs Ltd",
    specialty: "General Maintenance",
    rating: 4.6,
    reviews: 212,
    available: false,
    avatar: "SR",
    avatarColor: "#ff6b35",
    lat: 6.4698,
    lng: 3.2356,
    distance: "5.8 km",
    responseTime: "~25 min",
    skills: ["Tiling", "Painting", "Carpentry"],
  },
  {
    id: "eng_004",
    name: "Apex Electrical",
    specialty: "Industrial Electrical",
    rating: 4.8,
    reviews: 67,
    available: true,
    avatar: "AE",
    avatarColor: "#a855f7",
    lat: 6.5833,
    lng: 3.4333,
    distance: "7.4 km",
    responseTime: "~18 min",
    skills: ["Industrial Wiring", "Panel Upgrades", "Safety Audits"],
  },
  {
    id: "eng_005",
    name: "BuildRight Services",
    specialty: "Civil & Structural",
    rating: 4.5,
    reviews: 45,
    available: true,
    avatar: "BR",
    avatarColor: "#f59e0b",
    lat: 6.4481,
    lng: 3.4722,
    distance: "9.2 km",
    responseTime: "~30 min",
    skills: ["Roofing", "Foundations", "Structural Repairs"],
  },
  {
    id: "eng_006",
    name: "CoolTech HVAC",
    specialty: "Air Conditioning",
    rating: 4.9,
    reviews: 178,
    available: false,
    avatar: "CT",
    avatarColor: "#06b6d4",
    lat: 6.6018,
    lng: 3.3515,
    distance: "11.5 km",
    responseTime: "~35 min",
    skills: ["AC Installation", "AC Repair", "Duct Cleaning"],
  },
];

// Your user's current location — swap this with browser geolocation
// navigator.geolocation.getCurrentPosition(pos => { lat: pos.coords.latitude, lng: pos.coords.longitude })
export const USER_LOCATION = {
  lat: 6.5244,
  lng: 3.3792,
  label: "Your Location",
};
